### ISSUE TITLE
Процедура "НайтиКлиентТестирования"

### ISSUE THREAD

**Issue by ViktorErmakov** [lintest/1cWinCtrl#10]
Я вызвал эту процедуру до подключения клиента тестирования, указал порт 4800, получил в ответ не пустую строку в "возвращаемоеЗначение" а пробел
![изображение](https://user-images.githubusercontent.com/39617680/71321679-53710480-24ce-11ea-931c-580f86a6e8f7.png)

**Comment by ViktorErmakov** [comment]
Задумку понял

**Comment by lintest** [comment]
> Я вызвал эту процедуру до подключения клиента тестирования, указал порт 4800, получил в ответ не пустую строку в "возвращаемоеЗначение" а пробел

Проверю, должно возвращаться *Неопределено*

**Comment by lintest** [comment]
![](https://raw.githubusercontent.com/lintest/1cWinCtrl/errors/img/FindClient.png)

Не воспроизводится ошибка. Попробуй актуальную сборку.
https://github.com/lintest/1cWinCtrl/raw/errors/img/Example.epf

**Comment by ViktorErmakov** [comment]
хорошо

**Comment by ViktorErmakov** [comment]
В Вашей сборке все ок. Обновлю компоненту у себя в пул реквесте тогда.
Еще один момент, в описании написано что возвращаемое значение не обязательный параметр, однако без него не работает.

**Comment by lintest** [comment]
> Еще один момент, в описании написано что возвращаемое значение не обязательный параметр, однако без него не работает.

Необязательный, значит можно его не указывать при вызове функции. 
Так работает вызов внешней компоненты. Смотри на картинке выше.

**Comment by ViktorErmakov** [comment]
на картинке выше я как раз вижу в табло, что Вы передаете туда "данные", а вот я пробовал ничего не передавать, и получаю ошибку, что недостаточно параметров для функции.

**Comment by lintest** [comment]
Закрываю, поскольку ошибка не воспроизводится
