### ISSUE TITLE
добавить в компоненту возможность копировать информацию из буфера обмена

### ISSUE THREAD

**Issue by LevkinSergey** [lintest/1cWinCtrl#15]
В первую очередь интересуют конечно картинки

**Comment by lintest** [comment]
Что именно необходимо? Какой сценарий использования функции копирования?

**Comment by LevkinSergey** [comment]
сценарий такой. Делаем скиншот части экрана, потом рисуем на нем сразу. Я использую программу [falmeshot](https://flameshot.js.org/). После этого по нажатию какой-то кнопки вставляю картинку из буфера в присоединенные файлы справочника/документа.

Для винды есть компонента в документообороте. Для линукса удалось сделать через программу [irfanview](https://www.irfanview.com/) и запускать ее через wine, что не очень удобно.   

Если будет возможность реализовать задачу через компоненту, отпадет проблема установки лишнего ПО

**Comment by lintest** [comment]
Можно сделать,  используя библиотеку: https://github.com/dacap/clip

**Comment by lintest** [comment]
Сделал работу с буфером обмена для Windows, осталось сделать для Linux. Новый функционал можно посмотреть в примере обработки:
- копирование и вставка текста
- копирование и вставка картинки
- список доступных форматов
- очисика буфера обмена

**Comment by lintest** [comment]
Готово, осталось только описать в документации.
Работает копирование в буфер текста и картинок.
Поддержку остальных форматов сделаю позже.
Поддержка платформы Windows и Linux.

**Comment by LevkinSergey** [comment]
спасибо
