### ISSUE TITLE
Метод Сделать активным окно (дескриптор)

### ISSUE THREAD

**Issue by ViktorErmakov** [lintest/1cWinCtrl#17]
Когда мы делаем снимок экрана а не конкретного окна, я хотел бы сперва активировать то окно по значению дескриптора.

**Comment by lintest** [comment]
Для этого уже есть метод: АктивироватьОкно(Дескриптор), сейчас это не отражено в документации.

**Comment by ViktorErmakov** [comment]
Задачу закрываю. Метод есть, работает, необходимо его только отобразить в справке.
