### ISSUE TITLE
При попытке получить свойство "Формат" объекта ClipboardControl платформа вылетает

### ISSUE THREAD

**Issue by LevkinSergey** [lintest/1cWinCtrl#20]
Пробовал на 8.3.15.1700, 8.3.16.1296

**Comment by lintest** [comment]
Какая операционная система? Windows или Linux?

**Comment by LevkinSergey** [comment]
linux mint 19.3

Еще бы какой нибудь получить пример или документацию или ссылку где это можно посмотреть по методам ClipboardControl

**Comment by LevkinSergey** [comment]
Вот тут подсистема где пытаюсь реализовать работу с буфером с помощью вашей компоненты
https://github.com/cpr1c/clipboard_1c

**Comment by lintest** [comment]
Попробуйте новый релиз 0.09.8
