### ISSUE TITLE
Нужна возможность управлять окнами - размер, свёрнутость, максимизированность.

### ISSUE THREAD

**Issue by Pr-Mex** [lintest/1cWinCtrl#3]
Зная PID или заголовок окна надо уметь посылать ему команду для:
1. Свернуть/развернуть
2. Максимизирвать/минимизировать
3. Задать размер.

Это нужно для ОС Win и Linux.

**Comment by lintest** [comment]
Максимизировать и задать размер реализовано

**Comment by lintest** [comment]
Сейчас занимаюсь реализацией управления окнами для Linux. Вот как можно управлять окнами из командной строки, используя утилиту **wmctrl**:

```bash

# Список процессов с командной строкой
ps -fC 1cv8c

# Список окон с идентификаторами процессов и размерами
wmctrl -lpG

# Распахнуть окно по идентификатору 
wmctrl -i -r 0x02c001e0 -b toggle,maximized_vert,maximized_horz
```
