### ISSUE TITLE
Управление режимом отображения окна

### ISSUE THREAD

**Issue by lintest** [lintest/1cWinCtrl#7]
Для функций управления режимами отображения окна добавить второй параметр, который определяет нужно ли окно активировать. По умолчанию активировать не нужно.

РаспахнутьОкно(ДеактипторОкна, Активировать)

**Comment by Pr-Mex** [comment]
Есть ли возможность перед этим проверить статус окна, чтобы понять свёрнуто оно или нет?

**Comment by lintest** [comment]
> Есть ли возможность перед этим проверить статус окна, чтобы понять свёрнуто оно или нет?

Да, нужно сделать метод для получения текущего режима (статуса) отображения окна

**Comment by lintest** [comment]
Невозможно распахнуть окно, не активируя его.
