### ISSUE TITLE
Поиск клиента тестирования

### ISSUE THREAD

**Issue by lintest** [lintest/1cWinCtrl#9]
Реализовать метод для поиска клиента тестирования по номеру IP-порта, указанному в его командной строке. 

Метод должен возвращать идентификатор процесса и дескриптор основного окна.

**Comment by Pr-Mex** [comment]
Можно также получить всю строку запуска?

**Comment by lintest** [comment]
Предлагаю такой вариант, чтобы непосредственно функция возвращала дескриптор основного окна, а во второй параметр вызываемой функции возвращался JSON с идентификатором процесса, всей строчкой запуска и другими реквизитами процесса

**Comment by lintest** [comment]
Либо функция может возвращать JSON, где всё и сразу

**Comment by Pr-Mex** [comment]
Отлично!
